//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiDataBases
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationalOrganization
    {
        public int ObjectID { get; set; }
        public string Specialities { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
