//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int ObjectID { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Surname { get; set; }
    
        public virtual Learner Learner { get; set; }
        public virtual Object Object { get; set; }
    }
}
