//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationServer
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class Class
    {
        public int ClassId { get; set; }
        public string ClassName { get; set; }
        public string Formname { get; set; }
    }
}
