//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationServer
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class Faculty : IObject
    {
        public int ObjectID { get; set; }
        public string Dean { get; set; }
    
        public virtual EducationalOrganization EducationalOrganization { get; set; }


        public Nullable<int> ClassID
        {
            get { return EducationalOrganization.Organization.Object.ClassID; }
        }

        public Nullable<int> MajorID
        {
            get { return EducationalOrganization.Organization.Object.MajorID; }
        }

        public string Name
        {
            get { return EducationalOrganization.Organization.Object.Name; }
        }
    }
}
