//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationServer
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class Object : IObject
    {
        public int ObjectID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> MajorID { get; set; }
        public string Name { get; set; }
    
        public virtual Folder Folder { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Person Person { get; set; }
    }
}
